# Generated by Django 5.0.6 on 2024-10-24 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CostosIndirectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_costo', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cuenta_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SisContable.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_puesto', models.CharField(max_length=100)),
                ('salario_puesto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad', models.IntegerField(default=1)),
                ('salarios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SisContable.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('haber', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SisContable.cuenta')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SisContable.transaccion')),
            ],
        ),
    ]
