# Generated by Django 5.0.6 on 2024-11-04 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostosDirectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_puesto', models.CharField(max_length=100)),
                ('salario_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_empleados', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CostosIndirectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_costo', models.CharField(max_length=100)),
                ('monto_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto', models.DecimalField(decimal_places=2, max_digits=10, unique=True)),
                ('nombre_proyecto', models.CharField(max_length=200)),
                ('duracion', models.FloatField()),
                ('total_cd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_ci', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('esfuerzo', models.FloatField()),
                ('productividad', models.FloatField()),
                ('punto_de_funcion', models.FloatField()),
                ('total_empleado', models.IntegerField()),
                ('cd', models.ManyToManyField(related_name='proyectos', to='SisContable.costosdirectos')),
                ('ci', models.ManyToManyField(related_name='proyectos', to='SisContable.costosindirectos')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('haber', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SisContable.cuenta')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='SisContable.transaccion')),
            ],
        ),
    ]
