# Generated by Django 5.1.2 on 2024-11-06 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostoDirecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('salario_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_empleados', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CostoIndirecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(unique=True)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('cerrado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('puntos_funcion_total', models.PositiveIntegerField(help_text='Total de puntos de función del proyecto')),
                ('productividad', models.DecimalField(decimal_places=2, help_text='Puntos de función por persona-hora', max_digits=5)),
                ('duracion_total', models.DecimalField(blank=True, decimal_places=2, help_text='Duración en meses', max_digits=6, null=True)),
                ('esfuerzo_total', models.DecimalField(blank=True, decimal_places=2, help_text='Esfuerzo total en horas/persona', max_digits=10, null=True)),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, help_text='Costo total del proyecto', max_digits=12, null=True)),
                ('costos_directos', models.ManyToManyField(blank=True, related_name='proyectos_directos', to='SisContable.costodirecto')),
                ('costos_indirectos', models.ManyToManyField(blank=True, related_name='proyectos_indirectos', to='SisContable.costoindirecto')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('periodo_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='SisContable.periodocontable')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('haber', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SisContable.cuenta')),
                ('periodo_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='SisContable.periodocontable')),
                ('transaccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='SisContable.transaccion')),
            ],
        ),
    ]
